config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  patch 'cocktails/:id/reviews/:id/like', to: 'reviews#like', as: :like_review

  resources :cocktails, shallow: true do
    resources :doses, only: %i[create destroy]
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true,
                   uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true,
                   uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :rating, inclusion: { in: 1.0..5.0 }

  after_create :update_cocktail_rating

  def update_cocktail_rating
    new_rating = cocktail.reviews.reduce(0.0) { |total, review| review.rating + total } / cocktail.reviews.count
    cocktail.update(average_rating: new_rating.round(1))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @cocktails = Cocktail.all.shuffle
    @search = params.dig :search, :name
    @cocktails = Cocktail.where('lower(name) like ?', "%#{@search.downcase}%") if @search.present?
  end

  def show
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render 'new'
    end
  end

  def edit
    @dose = Dose.new
  end

  def update
    @cocktail.update(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to edit_cocktail_path(@cocktail)
    else
      render 'cocktails/edit'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to edit_cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@review.cocktail, anchor: "review-#{@review.id}")
    else
      @dose = Dose.new
      render 'cocktails/show'
    end
  end

  def like
    @review = Review.find(params[:id])
    @review.update(likes: @review.likes += 1)
    redirect_to cocktail_path(@review.cocktail, anchor: "review-#{@review.id}")
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for cocktail, html: { class: "row g-3" } do |f| %>
  <div class="col-md-5">
    <%= f.input :photo, label: false, input_html: { placeholder: "Name", class: "form-control" } %>
  </div>
  <div class="col-md-5">
    <%= f.input :name, label: false, input_html: { class: "form-control" } %>
  </div>
  <div class="col-md-2 d-grid gap-2">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<div class= "text-center py-3">
  <span class="show-title">Edit <%= @cocktail.name %> <i class="fas fa-mortar-pestle"></i></span>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-sm-5 col-12 d-flex justify-content-end pb-3">
    <%= cl_image_tag(@cocktail.photo.key, transformation: [ {crop: "crop", width: 900, height:900},
                                                          {width: 200, hight: 300, gravity: 'auto', crop: "fill", quality: 100}]) %>
  </div>
  <div class="col-sm-5 col-12 align-self-center">
    <% @cocktail.doses.each do |dose| %>
      <p>
        <%= "#{dose.description} of #{dose.ingredient.name}" %>
        <%= link_to dose_path(dose), method: :delete, remote: true do %>
          <i class="fas fa-minus-circle text-danger"></i>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

<div class="row d-flex justify-content-center py-3">
  <%= render "form", cocktail: @cocktail %>
</div>

<%= render "doses/new", cocktail: @cocktail, dose: @dose %>

<div class="my-3">
  <%= link_to cocktail_path(@cocktail) do %>
    <i class="fas fa-backward icon-link text-success"></i>
  <% end %>
</div>

app/views/cocktails/index.html.erb
<div class="container mt-4">
  <div class="row d-flex justify-content-center">
    <% @cocktails.each do |cocktail| %>
      <div class="col-sm-5 col-12 my-3">
        <%= link_to cocktail_path(cocktail) do %>

          <!-- Condicional para evitar que a página quebre quando o objeto não tiver uma imagem -->
          <% if cocktail.photo.present? %>
            <div class="card-category py-3" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.1), rgba(0,0,0,0.9)), url('<%= cl_image_path cocktail.photo.key, transformation: [{crop: "crop", width: 900, height:1400},{width: 200, height: 400, gravity: 'auto', crop: "fill", quality: 100}] %>')">
            <% else %>
              <div class="card-category py-3" style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.1), rgba(0,0,0,0.9)), url('https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1886&q=80')">
              <% end %>
              <%= cocktail.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

app/views/cocktails/new.html.erb
<div class= "text-center py-1">
  <span class="secondary-title fs-3">Create a new unique hipster drink</span>
</div>

<%= render "form", cocktail: @cocktail %>

<div class="my-3">
  <%= link_to cocktails_path do %>
    <i class="fas fa-backward icon-link text-success"></i>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class= "text-center py-3">
  <span class="show-title"><%= @cocktail.name %> <i class="fas fa-cocktail"></i></span>
  <p><%= @cocktail.average_rating ? "average rating: #{@cocktail.average_rating}" : "not yet rated" %></p>
</div>

<div class="row d-flex justify-content-center">
  <div class="col-sm-5 col-12 d-flex justify-content-end pb-3">
    <%= cl_image_tag(@cocktail.photo.key, transformation: [ {crop: "crop", width: 900, height:1400},
                                                          {width: 200, hight: 300, gravity: 'auto', crop: "fill", quality: 100}]) %>
  </div>
  <div class="col-sm-5 col-12 align-self-center">
    <% @cocktail.doses.each do |dose| %>
      <p><%= "#{dose.description} of #{dose.ingredient.name}" %></p>
    <% end %>
    <%= button_to "edit cocktail", edit_cocktail_path(@cocktail), method: :get, class: "btn btn-success" %>
  </div>
</div>

<hr>
<%= render "reviews/new", cocktail: @cocktail, review: @review %>
<hr>
<% if @cocktail.reviews.empty? %>
  <p class="text-center">No reviews here. Be the first hipster to write one!</p>
<% else %>
  <div class="d-flex justify-content-center flex-wrap">
    <% @cocktail.reviews.order("likes DESC").each do |review|%>
      <div id="review-<%= review.id %>" class="col-12 col-sm-5 m-2 d-flex justify-content-center">
        <div class="card border-success mb-1" style="width: 40rem;">
          <div class="card-header text-white bg-success mb-1">
            <%= link_to like_review_path(review), method: :patch, remote: true do %>
              <i class="fas fa-thumbs-up text-white"></i>
            <% end %>
            (<%= review.likes %>)
          </div>
          <div class="card-body text-success">
            <p class="text-end"><%= "rated: #{review.rating}" %></p>
            <p class="card-text"><%= review.content %></p>
            <h5 class="card-title"><%= "by #{review.user}" %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="my-3">
  <%= link_to cocktails_path do %>
    <i class="fas fa-backward icon-link text-success"></i>
  <% end %>
</div>

app/views/doses/_new.html.erb
<div class= "text-center py-1">
  <span class="secondary-title fs-3">Add a new dose</span>
</div>
<%= simple_form_for [cocktail, dose], html: {class: "row g-3"} do |f| %>
  <div class="col-md-5">
    <%= f.input :description, label: false, input_html: { placeholder: "Add a description here...", class: "form-control" }, as: :string %>
  </div>
  <div class="col-md-5">
    <%= f.association :ingredient, collection: Ingredient.order('name'), include_blank: "Choose an ingredient...", include_hidden: false, label: false, input_html: { class: "form-control" } %>
  </div>
  <div class="col-md-2 d-grid gap-2">
    <%= f.submit "add dose", class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch #538 - Marcelinho's Hipster Cocktails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reviews/_new.html.erb
<div class= "text-center py-1">
  <span class="secondary-title fs-3">Review this cocktail</span>
</div>
<%= simple_form_for [cocktail, review], html: { class: "row g-3" } do |f| %>
  <div class="col-12">
    <%= f.input :content, label: false, input_html: { placeholder: "Add your review here...", class: "form-control-sm w-100" } %>
  </div>
  <div class="col-md-6">
    <%= f.input :rating, collection: [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5], include_blank: "Choose a rating...", include_hidden: false, label: false, input_html: { class: "form-control" } %>
  </div>
  <div class="col-md-6">
    <%= f.input :user, label: false, input_html: { placeholder: "Your name", class: "form-control" } %>
  </div>
  <%= f.submit "review", class: "btn btn-success"%>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <div class="col-12 col-sm-5 text-wrap text-center">
      <%= link_to "Marcelinho's Hipster Cocktails", root_path, class:"ms-3 page-title text-success" %>
    </div>
    <div class="col d-flex justify-content-center flex-wrap">
      <div class="row p-1 align-self-center">
        <%= button_to "create a new cocktail", new_cocktail_path, method: :get, class: "btn btn-success"%>
      </div>
      <div class="row p-1 align-self-center">

        <!-- usando simple form sem um model e com uma url específica -->
        <%= simple_form_for :search, url: cocktails_path, method: "GET", html: { class: "d-flex" } do |f| %>
          <div class="input-group">
            <%= f.input :name, label: false, input_html: { placeholder: "Find a cocktail", value: nil, class: "form-control me-2" } %>
            <%= f.submit "search", class: "btn btn-outline-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>